name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mostrar arquivos do repositório
        shell: pwsh
        run: |
          Get-ChildItem -Recurse

      - name: Mostrar conteúdo do main.py
        shell: pwsh
        run: |
          Get-Content main.py

      - name: Mostrar conteúdo do gui.py
        shell: pwsh
        run: |
          Get-Content gui.py

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          python -m PyInstaller --clean --log-level DEBUG --onefile --windowed --add-data "config.json;." --name EtiquetaA5 main.py

      - name: Upload EXE
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: EtiquetaA5-Windows
          path: dist/EtiquetaA5.exe